### ISSUE TITLE
How to remove "schemas-upnp-org:device" from Notify Device Type Messages

### ISSUE THREAD

**Issue by pkuehnel** [Yortw/RSSDP#102]
I want to use RSSDP to get my car's charging Station discovered by a smart Meter. The problem is, the smart meter only listens to device Type `NT: urn:schemas-simple-energy-management-protocol:device:Gateway:1` but RSSDP always adds `schemas-upnp-org:device:`

![notify deviceType](https://user-images.githubusercontent.com/35361981/90334243-92f3e000-dfcc-11ea-9212-adaa781bd051.JPG)

How can I get rid of it?

**Comment by pkuehnel** [comment]
OMG I am so stupid... commented out the Line of DeviceTypeNamespace...

**Comment by Yortw** [comment]
Nah, not stupid, just using a new lib... happens to us all. Glad you got it figured out tho :)
