### ISSUE TITLE
Functions of single device not grouped

### ISSUE THREAD

**Issue by mterwoord** [Yortw/RSSDP#18]
I have a device (Silvercrest internet radio, see http://www.silvercrest-multiroom.de/en/products/stereo-internet-radio/) which RSSDP sees as 6 separate devices. I'm not sure how to group these together, so I can see a nice logo etc. How can I diagnose this?

**Comment by Yortw** [comment]
If you parse the USN property of each discovered device, and take the first section up to :: then I believe that gives you a common key for each device. If there is no :: in the string, then just use the whole string.

Alternatively, search only a specific type of device (what type depends on what you need, in your case you might want only renderers or sources etc.). Root devices are a good way to go as their service description will contain all the sub devices anyway, but you'll only get the root device returned in the top level search results.

**Comment by Yortw** [comment]
Did you manage to achieve the grouping you wanted using my advice?

**Comment by mterwoord** [comment]
Not yet, it's still on my to do list, but have other things on it. Will let you know.. :)

**Comment by Yortw** [comment]
Closing this because it's not really an issue with the library itself (the SSDP devices are exposed multiple times/ways over the SSDP protocol), and the issue is old. Feel free to reopen or comment when you need assistance again.
