### ISSUE TITLE
Can't discover device using SsdpDeviceLocator

### ISSUE THREAD

**Issue by markjerz** [Yortw/RSSDP#19]
Hi,

So, I've got an application running that publishes itself using SsdpDevicePublisher. I have another application running SsdpDeviceLocator.

Now when I just run both these apps from the same windows machine the locator discovers the publisher. However, if I run the publisher on a raspberry pi (via mono) I can't see it from the locator. 

Any thoughts on why this might be?

The odd thing is that windows can see the raspberry pi service as it shows up in my network folder!

**Comment by Yortw** [comment]
I want to help solve this problem, but I'm unfamiliar with Mono and Linux, I don't have Mono setup anywhere and I don't own a Linux device I can do dev on, so at the moment the best I can do is provide suggestions (sorry).

I think the fact the Pi shows in Windows is probably irrelevant except to say it's on the network - I believe Windows usings a number of different networking protocols, so it could be finding the Pi through some other mechanism - **unless it's only showing up when you run the publisher?**

Here's a few things I would check;

- Is there any kind of firewall etc. on the Pi that might be blocking the UDP messages used by SSDP? For that matter, is there the firewall on the other machine is blocking the outgoing UDP messages?

- Is there any other SSDP software running on the devices? Windows for example has an SSDP service that sometimes runs, and if it runs first it often swallows all the SSDP messages and doesn't share with anyone else. I guess this could happen on Linux too?

- Do both machines have IPV4 addresses? At the moment RSSDP doesn't support IPV6, so it's not going to work if either of the machine is IPV6 only.

- Are both publisher and locator binding to the same adapter/subnet? If either the Pi or your other machine have multiple network adapters in them, it's possible they're broadcasting/listening on different subnets/networks. Try using the overloaded constructors to specific the local IP you want to bind to, and ensure the IPs your provide to both are on adapters/subnets that should see each other.

Let me know the answers to those issues and if we haven't solved it I'll do some more thinking.
Thanks.

**Comment by markjerz** [comment]
Wow, thanks for the prompt and superb response. I'll try some of those things tomorrow and let you know. 

In windows explorer it's actually showing the service that I'm publishing, not just the pi, which is promising at least!

**Comment by Yortw** [comment]
No problem :)

"In windows explorer it's actually showing the service that I'm publishing, not just the pi, which is promising at least!"

Ah, well in that case it's *likely* a problem on the locator end. Checking the firewalls, bound IP and the Windows SSDP service are all still good idea.s

**Comment by Yortw** [comment]
Hi, any luck?

**Comment by Yortw** [comment]
Closing due to lack of response. Please feel free to reopen if this is still an issue for you. There have been some other similar issues with solutions posted, so you might like to try check those first.
