### ISSUE TITLE
Bound to wrong IPAddress

### ISSUE THREAD

**Issue by kakone** [Yortw/RSSDP#2]
Hello,

_Socket.Bind(new IPEndPoint(IPAddress.Any, _LocalPort) can bind sometimes to a wrong network address (on my computer, I have several network cards and sometimes, it choose the wrong local IP address). In the documentation of Socket.Bind method, you can see : "using IPAddress.Any as the address parameter, and the underlying service provider will assign the most appropriate network address".
So I replaced by _Socket.Bind(new IPEndPoint(Dns.GetHostAddresses(Dns.GetHostName()).Where(address => address.AddressFamily == AddressFamily.InterNetwork).First(), _LocalPort)); because the first IPAddress is the good one for me but the good solution would be to create an UdpSocket for each local IP address.

Cordially,
Stéphane.

**Comment by Yortw** [comment]
Interesting. I wonder how the system decides which is the 'most appropriate' adapter/address to choose?

I will have to mull this issue over. I don't believe, off hand, that connecting to every IP address/adapter in the system would be a good idea. Other adapters may be for WAN networks, VPN connections or bridges to other local but hostile networks (DMZ machines). It might be that you explicitly don't want to search or publish on some networks, or even that you want to search/publish different devices on each network. Even in the case of ipv4/6 (if we supported 6), there might be reasons you might want to limit scope to one or other(?).

I think the best answer would be for the client using the library to decide what they want to do on each adapter/address and create a locator and/or publisher object for each one. Either that or be able to pass an enumerable of addresses/adapters to listen on. That is more convenient if you want to do the same thing on multiple addresses, but not so useful when you want to do different things for each. The current design doesn't allow the client to specify the address or adapter in any case. 

At the moment the logic and code for the address (use of .Any) is typically in the UdpSocket class for each platform, and that is created by the platform specific socket factory class. To make it easier for people to use the library, the platform specific versions of the locator/publisher have default constructors that create a default communications server instance, which in turn creates a default socket factory instance. I'm not sure adding the new arguments to the constructor of the factory & socket is a satisfactory design. Adding them to the higher level constructors and passing them down may be the best solution, but feels like poor encapsulation.

I will think on this and see if I can decide on a good solution. Advice is welcome.

Thanks.

**Comment by Yortw** [comment]
Interesting. The documentation for IPAddress.Any (https://msdn.microsoft.com/en-us/library/vstudio/system.net.ipaddress.any(v=vs.100).aspx) suggests that it should already be listening on ALL interfaces (which makes sense given the name). I assume this is not what you're experiencing? Which platform are you running on (I presume .Net 4 Framework)?.

**Comment by Yortw** [comment]
This explains how the 'most apppropriate' address is chosen on various versions of Windows;

http://blogs.technet.com/b/networking/archive/2009/04/25/source-ip-address-selection-on-a-multi-homed-windows-computer.aspx

Are you having problems with the locator or publisher choosing the wrong address (I assume publisher), and what is the symptom? The evidence here suggests that 'listening' on IPAddress.Any should listen on all addresses anyway, and outgoing packets will always have the 'best' source IP assigned, and use route table to get message to where it needs to go, regardless of what address is passed to bind. That makes it seem like there should be no issue with the way the code currently is. 

Also, what OS are you using?

**Comment by kakone** [comment]
I'm using Windows 8.1 and I have problems with the locator. If I let IPAddress.Any, none device is found but if I indicate the good IPAddress manually, it works (other network cards are for VirtualBox or VMWare). If you look at the Ssdp class in http://opentools.homeip.net/dev-tools-for-upnp, they do a foreach on all local IP addresses.

When you do a Bind, IPAddress.Any don't listen on all addresses, but only on the 'most appropriate' which is not the most appropriate for me :-)

**Comment by Yortw** [comment]
I would love to see this fixed, but do not have time at present to do it myself. If anyone wants to contribute, feel free. This is likely a difficult issue to solve though. Here are some thoughts;

First, we need to understand the problem. I suspect the server is listening on all interfaces (based on https://msdn.microsoft.com/en-us/library/vstudio/system.net.ipaddress.any(v=vs.100).aspx) but the client is sending on an interface that doesn't support multicast, or doesn't route correctly or whatever. That's only a guess though. Fixing this issue starts with understanding the details. The behaviour is specifically mentioned as varying on different versions of Windows (and then there's iOS and Android to consider). The two MS articles linked previously in this thread also disagree with each other (though my assumption is one refers to client behaviour and the other to servers). Without understanding this in detail, we're likely to do the wrong thing, I think.

Secondly we need to consider how this should work from a consumer's point of view. I feel not all consumers will want to use all interfaces, so if we're going to support this we should provide a mechanism for specifying which addresses/adapters etc. to use. At this point our options are either to accept some kind of IEnumerable of addresses to support, or to force the consumer to create a separate server/client for each address. I actually favour the later. It keeps the library code simpler internally, I suspect it is easier for clients to reason about (if more work to implement) and it eliminates some other problems with the object model that occur with the other design. I could be wrong however. In any case, we need to decide what to accept (an address, an adapter, a subnet?) and then whether we can use a type already common across platforms (.Net, UWP, WinRT, Xamarin.iOS, Xamarin.Android etc) or whether we need to wrap those types in some kind of common interface etc.

Finally, if we do implement multiple addresses inside a single server/locator then we need to update the object model (we probably should anyway). The SSDP specification says the address of a service returned to a client must match the address the client request was received on. That means we really should have multiple addresses for each published device, and we'll need to use the right one for each request and when broadcasting notifications. This would be a breaking interface change and will require a new major release. So we need multiple service addresses, and a way to tie those back to the addresses/adapters being listened to by the server. An alternative might be to have a single relative address for the device and return an absolute uri based on a root using the device address and port. That still might not support every use case though.

**Comment by thunder7553** [comment]
I have a Problem with multiple Interfaces as well. I have no common host name that is accessible from all networks the same way, so I need a possibility to define the description document for each Interface. I think the easiest way to implement this would be to offer an IP Address in the constructor, and use IPAddress.any as the default value. this would not break existing code and still allow consumers of the library a more finegrained Control.

**Comment by Yortw** [comment]
Hi,

Thanks for the feedback, I appreciate it :smile: 

Just to clarify, you are suggesting;

1. Pass IP (optionally), and if neccesary use it to find the adapter.
2. A separate Publisher/Locator instance for each interface the library consumer wants to publish/listen on? (as opposed to multiple addresses in one object instance).

**Comment by thunder7553** [comment]
Yes. There are other things to manage as well, especially if the publisher is running as a service. IP addresses and network Interfaces can change while the Server is running. So having this possibility would be a good start.

**Comment by Yortw** [comment]
It should now be possible to specify an IP address on the constructor to the socket factory.  So something like this;

```c#
var locator = new Rssdp.SsdpDeviceLocator(new Rssdp.Infrastructure.SsdpCommunicationsServer(new Rssdp.SocketFactory("192.168.1.200")));
```

Creating a publisher is similar. This should bind the sockets created to the address (and associated adapter) specified. By default, or if null/empty string is passed for the IP, the system continues to use IPAddress.Any.
