### ISSUE TITLE
Microsoft.Bcl.Build warnings and errors

### ISSUE THREAD

**Issue by tur0kk** [Yortw/RSSDP#24]
I'm developing some sort of framework, which includes this one for the service discovery.
When referencing my framework from an end user project (WPF/UWP), I get warnings and errors. This come from Microsoft.Bcl.Build which is a dependency of RSSDP:

- Error: Could not locate path/to/packages.config. Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.
- Warning: All projects referencing MyFramework.csproj must install nugget package Microsoft.Bcl.Build

I tried to suppress these warnings (see [stackoverflow](http://stackoverflow.com/questions/17180268/warning-all-projects-referencing-myproject-csproj-must-install-nuget-package-m), but this just added another error:

- The OutputPath property is not set for project...

Do you have any experiences with those?

**Comment by Yortw** [comment]
Hi,

I have only seen those warnings when either the projects referencing another project that uses Microsoft.Bcl.Build (in this case RSSDP) do not also reference it, or if the referenced version is an old one.

Every time I've seen the problem, using Nuget to add the Microsoft.Bcl.Build (v1.0.21) and sometimes the latest Microsoft.Bcl.Async package has fixed it.

Hopefully that works for you too.

**Comment by Yortw** [comment]
Closing as no follow up, and adding the specified nuget to the other projects should fix this.
If it doesn't, please feel free to reopen.
