### ISSUE TITLE
Cannot publish or search on macOS/Linux using .NET Core

### ISSUE THREAD

**Issue by stickybun** [Yortw/RSSDP#33]
I have just run into this issue [Cannot set udpClient.ExclusiveAddressUse = false in macOS and Linux](https://github.com/dotnet/corefx/issues/11292) whilst testing the .NET Standard library on non-Windows platforms.

This actually prevents publishing/searching altogether as you get an exception: 

> Unhandled Exception: System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_ExclusiveAddressUse(Boolean value)
   at Rssdp.SocketFactory.CreateUdpMulticastSocket(String ipAddress, Int32 multicastTimeToLive, Int32 localPort)

However, changing the code from [SocketFactory.cs#L87](https://github.com/Yortw/RSSDP/blob/cdef739640/src/Main/Shared/SystemNetSockets/SocketFactory.cs#L87) as follows:
```csharp
#if NETSTANDARD1_3
	if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Windows))
	{
		retVal.ExclusiveAddressUse = false;
	}
#else
	retVal.ExclusiveAddressUse = false;
#endif
```

Allows publishing and searching, but until the [Rework ExclusiveAddressUse and ReuseAddress on non-Windows platforms](https://github.com/dotnet/corefx/pull/11509/files) commit makes in into a release, a simultaneous publish and search will throw an 'Address in use' exception on non-Windows platforms.

**Comment by Yortw** [comment]
That's unfortunate, but not sure there's anything we can do until the framework is updated :(
I don't have any non Windows machines I can test on, so I'll have to rely on your and other contributors to find and submit fixes for issues like this.

Thanks fo the PR. It's been merged and published now.
