### ISSUE TITLE
Missing MX/Man Support

### ISSUE THREAD

**Issue by Yortw** [Yortw/RSSDP#40]
Some devices do not send MX/MAN headers in search requests. The SSDP specification says messages missing these should be ignored, however this just leads to a system that doesn't work.

Suggested solution is to add a StandardsMode property to the SsdpPublisher of an enum type (SsdpStandardMode) with one of the following options;

- Default - probably should be treated as 'Relaxed' so it just works out of the box for most consumers.
- Strict - Strictly obeys the standard, ignoring requests missing the required headers.
- Relaxed - Uses a sensible default when the MX/MAN headers etc are missing.

It is further suggested that if other standard vs. reality issues occur this same flag is used to determine appropriate behaviour. A similar property may also be added to the SsdpDeviceLocator in the future if similar problems are found in that area.

**Comment by Yortw** [comment]
@LukePulverenti Does this sound like a good fix to you?

**Comment by LukePulverenti** [comment]
Yes I think this is a Stict/Relaxed mode option is a good idea. Going forward when this happens I will make sure to capture the knowledge of exactly what devices this applies to.

**Comment by Yortw** [comment]
@LukePulverenti Hey Luke, could you send me an email I can reply to (email should be visible on my profile I think). I'd like to discuss some of the changes you've made in the Emby copy of RSSDP and I'm not sure it's worth opening issues just for the discussion.

**Comment by Yortw** [comment]
Should be closed by latest commit (dc64e02fc369e540023f1681e594873532ad2e92) but only published as pre-release package at the moment.
