### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Yortw** [Yortw/RSSDP#44]
Because of support for older platforms such as .Net 4.0 and WP 8.0, RSSDP has a dependency on the Async/BCL libraries from Microsoft. These dependencies are not neccesary on newer platforms.

Now that RSSDP uses the bait and switch technique, it should be possible to create a PCL supporting only the newer platforms and drop the dependencies from both the referenes and the nuget target for those platforms while keeping them for the older ones.

Given the BCL libs are somewhat cancerous, in that anything that if project A reference project B and project B references the BCL, then project A (and anything referencing it) also needs to reference BCL or suffer compiler warnings, dropping the dependencies where not required would be a great idea.

**Comment by Yortw** [comment]
This should be merged into the main trunk now, though still pending a Nuget release.

**Comment by Tapanila** [comment]
Any plan for nuget release with this change? Would love to get rid BCL libraries :)

**Comment by Yortw** [comment]
Yes I do plan to release it, but not sure when. Was thinking about putting up a pre-release package for testing before doing an official one.

You may find the latest stable package already drops the BCL dependencies for your package. It now supports .Net Standard 1.3 without depdencies, and .Net Standard 1.3 is used in preference to many existing targets so you may not need a new package.

**Comment by Yortw** [comment]
@Tapanila Hi, have pushed a pre-release version of the package that should eliminate the dependencies if you want to try that. Not planning a full release until I've managed to make some other changes (though as I said before the current stable package does get rid of dependencies on some plats).

**Comment by Tapanila** [comment]
Thanks. Will give it a try
