### ISSUE TITLE
await DiscoveredDevice.GetDeviceInfo() fails

### ISSUE THREAD

**Issue by Rambalac** [Yortw/RSSDP#54]
Calling ```GetDeviceInfo()``` in ```MessageReceived``` fails with ```HttpRequestException``` for some devices.
Inner exception is ```ComException``` without any message in ```System.Net.Http.HttpClientHandler```.
Using it in UWP application.

After searching some info I found some solution about proper handling http redirection. 

For now workaround is to ignore this exception.

**Comment by Yortw** [comment]
Unfortunately I am unable to reproduce this on any of the networks I have access to, so fixing it is hard. I do not want to just suppress an error in the library as it may be important to the calling code to know that device failed etc. 

**can you provide me with links to the articles you mention? If they have better solutions that just suppressing the error then maybe I can implement those**

Current work arounds are:

1. Suppress the error like you are.

2. Don't use GetDeviceInfo - it's just a wrapper around HttpClient doing a get to the service DDD url anyway, so you can easily write your own code to retrieve the DDD and then you can configure the http client however you need to 'properly handle redirects'. Curiously I don't know what that means, I haven't had time to check but I thought the default configuration enabled automatically following redirects, in which case redirects should be handled anyway... hence the request for the links to the articles.

You could also try using *WebSocketError.GetStatus* on the hresult of the exception to see if that gives you a specific HTTP or network related error. Sample from the MS help page (https://docs.microsoft.com/en-us/uwp/api/Windows.Web.WebErrorStatus);

```c#
    WebErrorStatus status = WebSocketError.GetStatus(ex.GetBaseException().HResult);
```

**Comment by Rambalac** [comment]
It returns WebErrorStatus.ConnectionReset

**Comment by Yortw** [comment]
Interesting. Seems like the remote device is terminating the connection for some reason, but not sure. Doesn't seem like a redirect issue, unless that happens after too many redirects? If that's the case I still believe it's up to the caller to catch and handle the error (even if that just means suppressing it in their case).

Do you have links to the previous articles you mentioned about the redirect issue?

**Comment by Yortw** [comment]
I assume if you do your own HTTP get to that device url the same thing happens?

**Comment by Rambalac** [comment]
Actually Netgear router is the cause. ```http://192.168.11.1:8200/rootDesc.xml``` returns Connection rest in Chrome. Router has USB for file server but it's not used.

**Comment by Yortw** [comment]
Right. Good to know the cause, again I don't think the library should suppress these errors. The client code using the library may want to report the device inaccesible etc, so it should catch them and deal with them as it sees fit. Thanks for reporting and helping to diagnose though.

**Comment by Rambalac** [comment]
How about ```<exception cref="">```?

**Comment by Yortw** [comment]
Sure, could/should update the docs. Exception is different on different platforms though, (UWP just uses system.exception as you found), and I'm not sure if there are other exception types that may be thrown.
