### ISSUE TITLE
SsdpDevicePublisher not available for Xamarin?

### ISSUE THREAD

**Issue by ovesennet** [Yortw/RSSDP#71]
Hi and thanks for your great work.

I use rssdp and SsdpDevicePublisher with success in a windows (uwp) app. Now I want to use it on IOS/tvOS using Xamarin (Visual Studio for Mac).

However, the class SsdpDevicePublisher does not exist in this environment. All other classes exist, and I can use SsdpDeviceLocator with success.

I use version 3.5.7

Any ideas on why SsdpDevicePublisher is not available?

**Comment by Yortw** [comment]
Could be when I re-instated the Xamarin projects over the net core version I missed including a file or something. I'll recheck.

In the meantime, if you're *not* using a PCL for your project you may be able to work around this by manually referring the net core assembly for RSSDP instead of the Xamarin specific ones.

**Comment by Yortw** [comment]
I have created SsdpDevicePublisher classes for the Xamarin projects, but I am not currently able to test them. If you could check and confirm they work that would be great, thanks. Pre-release package available on Nuget;

```ps
     Install-Package Rssdp -Version 3.5.8-Alpha
```

**Comment by ovesennet** [comment]
I can confirm that publishing works using 3.5.8. At least in the simulator on my Mac. Thanks a lot ;-)

**Comment by Yortw** [comment]
Thanks for your help. I will try to find time soon to test the Android version and then publish a non-release package when confirmed.

**Comment by Yortw** [comment]
Official packaged released, should work on both platforms.
Thanks for reporting :)
