### ISSUE TITLE
How can i launch iOS Project on Device or Simulator?

### ISSUE THREAD

**Issue by quantumarun** [Yortw/RSSDP#73]
When i open the Rssdp.iOS project i don't see any info.plist, AppDelegate.cs, Main.cs which is required to test on iOS device. Is there any Test iOS project which can be used to launch on device?

**Comment by Yortw** [comment]
The Rssdp.iOS project is the library, not an app, so it doesn't have an info.plist or AppDelegate.cs as it doesn't need them. You don't run the library directly.
It should be easy enough to put together your own sample app using the quick start guides. I don't appear to have a sample for iOS at present.
