### ISSUE TITLE
How to Find List Of Devices Which connected with same network using RSSDP

### ISSUE THREAD

**Issue by vishalsgithub** [Yortw/RSSDP#79]

**Comment by Yortw** [comment]
Hi,

Have you tried the sample code from the readme.md file, particularly the bit labelled 'simple search'?
Did that not work or do you have a problem with it?

**Comment by vishalsgithub** [comment]
Simple search return 10 item and all are same and it's all are router IP and Name .

**Comment by vishalsgithub** [comment]
i want all device which is connected with Router or network

**Comment by Yortw** [comment]
It's possible that's the only device on your network that supports SSDP then. There are different protocols supported by different devices, no guarantee a single protocol will find them all. It would be odd for RSSDP to correctly locate the router and not locate other devices that support the SSDP protocol, though I guess there could be a bug I don't know about. Unfortunately I don't have access to your network and it works on all of the networks I have access to, which makes it hard to diagnose.

Have you tried any other SSDP based utilities, do they find anything else?

**Comment by vishalsgithub** [comment]
i tried Ping Method but Ping only return Ip address and i want IpAddress, HostName and mac address

**Comment by vishalsgithub** [comment]
Have you any other method which find hostname and mac address by IP

**Comment by Yortw** [comment]
Try the Intel UPnP utilities, in particular Device Spy, and see if they can fin anything this doesn't.

SSDP won't give you device MAC's anyway (necessarily), that's not part of the protocol. It possibly won't even give you the host name, the protocol is designed for finding the address of devices that support the SSDP protocol so you can make requests to them. 

I think what you are looking for is a lower level network utility, not what this library is designed to do. I do not know of such a library, though I presume something to do that job exists.
