### ISSUE TITLE
Listen for SSDP on Multiple NICs

### ISSUE THREAD

**Issue by Steve0212a** [Yortw/RSSDP#85]
I read your FAQ and saw the sample for selecting one NIC (ip address) to listen on.  However, I want to listen on multiple NICs simultaneously.  Is that possible?  I think I would just have to create one SsdpCommunicationsServer for each IP Address on the multiple NICs.

What would be the recommended approach to do this?

Thanks.

**Comment by Yortw** [comment]
Hi,

Yes, at the moment you need to create a separate publisher or device locator, using a separate SsdpCommunicationsServer, for each IP. 

Finding an alternate solution for this has been on the list for a while, but there are numerous challenges and I do not know if or when I will be able to implement a solution. In the mean time, creating a separate instance for each IP is the only solution I have for you.

**Comment by Steve0212a** [comment]
ok - thanks
