### ISSUE TITLE
Broadcast / Publishing not working, can't be seen in OSX, Linux or Windows

### ISSUE THREAD

**Issue by dbuzz111** [Yortw/RSSDP#92]
Been at this for days, and I cannot for the life of me get publishing to show up.

I've read all the issues top to bottom, I feel this must be me, somehow I am bonkers.

Anyone able to suggest or point to what I am doing wrong.

Below is the complete code I have been trying to use on Linux.

Thank you very much!

[rrsdp.txt](https://github.com/Yortw/RSSDP/files/2892206/rrsdp.txt)

**Comment by Yortw** [comment]
Hi,

Unfortunately it is typically very hard to diagnose this stuff remotely. First things to check (especially for Windows Explorer) are listed in the [FAQ](https://github.com/Yortw/RSSDP/wiki/Frequently-Asked-Questions) - have you checked that?

Is your firewall blocking either the publisher sending packets out, or the incoming requests for the device description document? Are you able to manually request the DDD from the client devices using a browser and see the XML returned?

Are all devices on the same network (wifi or lan), or are you trying to go across wifi/lan or different wifi/lan segments? (there can be issues doing this, depending on hardware and settings I think).

Does the DDD document returned match *exactly*  with the publisher settings? (some systems won't show devices if the URLs, usns, serial numbers etc. don't match)

Does the device published by the sample app show?

Can you find the device using an RSSDP client even if it doesn't show in the OS? RSSDP is typically less fussy about the DDD matching etc. and IMHO has fewer quirks (at least than Windows), so if this can find it we're probably looking at a configuration/mismatch issue, if it can't find it then it may be firewall/network related etc.

**Comment by sonicmouse** [comment]
I was having the same issue, so i did the UDP/multicast from scratch and it works. So there is definitely something wrong with the library itself.

I think there may be issues with binding. I did notice the library binding to the wrong IP address for listening. I have multiple interfaces on my computer:

Windows IP Configuration
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : dcim.local
   Link-local IPv6 Address . . . . . : fe80::c022:fe53:e146:4696%20
   IPv4 Address. . . . . . . . . . . : 10.16.129.76
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . : 10.16.10.1

Wireless LAN adapter Wi-Fi Main:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Ethernet adapter vEthernet (Hyper-V Virtual Ethernet Adapter):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::7869:eb7:d32e:2b6c%22
   IPv4 Address. . . . . . . . . . . : 172.18.60.33
   Subnet Mask . . . . . . . . . . . : 255.255.255.240
   Default Gateway . . . . . . . . . :

What this library was doing is using the vEthernet adapter, but it should be using the first one in the list. How would you force it to use the proper ethernet adapter?

**Comment by Yortw** [comment]
Closing as no response.
